[dev]
  port = 3988
  publish = "public"

[build]
  command = "make -j build && make -B html"
  publish = "public/"
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "12"
  RUBY_VERSION = "2.6.2"

[[redirects]]
  from = "https://example.netlify.com"
  to = "https://example.org"
  status = 301
  force = true
