[dev]
  port = 3988
  publish = "public"

[build]
  command = "make -j build && make -B html"
  publish = "public/"
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "17"
  RUBY_VERSION = "3.0.3"
