#!/usr/bin/env python3
"""Self-host a subset of the Hugeicons icon font.

The site only uses a couple dozen icons, so instead of letting every page block
on the full ~660KB font from cdn.hugeicons.com we ship a tiny subset from our
own origin. This script:

  1. Scans src/**/*.plim for the `hgi-*` classes actually used.
  2. Pulls the full Hugeicons CSS + woff2 (cached under .cache/hugeicons).
  3. Subsets the font down to the used glyphs with pyftsubset.
  4. Writes public/static/fonts/hugeicons/{hgi-stroke-rounded.woff2,hugeicons.css}.

Run it whenever you add or remove an icon:

    make icons

Outputs are committed, so a normal `make build` does not need network access.
"""

from __future__ import annotations

import re
import subprocess
import sys
import urllib.request
from pathlib import Path

CDN_CSS = "https://cdn.hugeicons.com/font/hgi-stroke-rounded.css"
CDN_WOFF2 = "https://cdn.hugeicons.com/font/hgi-stroke-rounded.woff2?t=1721855138058"

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
CACHE = ROOT / ".cache" / "hugeicons"
OUT_DIR = ROOT / "public" / "static" / "fonts" / "hugeicons"
WOFF2_OUT = OUT_DIR / "hgi-stroke-rounded.woff2"
CSS_OUT = OUT_DIR / "hugeicons.css"

# `hgi-stroke` is the base class and `hgi-stroke-rounded` the font family; neither
# is an icon, so they never get a glyph rule.
BASE_CLASSES = {"hgi-stroke", "hgi-stroke-rounded"}

ICON_RE = re.compile(r"hgi-[a-z0-9-]+")
RULE_RE = re.compile(r"\.hgi-stroke\.(hgi-[a-z0-9-]+):(before|after)\{(content:\"[^\"]*\"[^}]*)\}")


def fetch(url: str, dest: Path) -> Path:
    if not dest.exists():
        dest.parent.mkdir(parents=True, exist_ok=True)
        print(f"  downloading {url}")
        urllib.request.urlretrieve(url, dest)
    return dest


def used_icons() -> list[str]:
    found: set[str] = set()
    for plim in SRC.rglob("*.plim"):
        for match in ICON_RE.findall(plim.read_text(encoding="utf-8", errors="ignore")):
            found.add(match)
    return sorted(found - BASE_CLASSES)


def main() -> int:
    css_src = fetch(CDN_CSS, CACHE / "hgi-stroke-rounded.css").read_text(encoding="utf-8-sig")
    woff2_src = fetch(CDN_WOFF2, CACHE / "hgi-stroke-rounded.woff2")

    # name -> list of (pseudo, body) for every glyph rule in the full CSS
    rules: dict[str, list[tuple[str, str]]] = {}
    for name, pseudo, body in RULE_RE.findall(css_src):
        rules.setdefault(name, []).append((pseudo, body))

    icons = used_icons()
    missing = [i for i in icons if i not in rules]
    if missing:
        print(f"error: icons used in src but absent from Hugeicons: {missing}", file=sys.stderr)
        return 1

    codepoints: set[int] = set()
    for icon in icons:
        for _pseudo, body in rules[icon]:
            for ch in re.search(r'content:"([^"]*)"', body).group(1):
                codepoints.add(ord(ch))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    unicodes = ",".join(f"{cp:04x}" for cp in sorted(codepoints))
    subprocess.run(
        [
            "pyftsubset", str(woff2_src),
            f"--unicodes={unicodes}",
            "--flavor=woff2",
            f"--output-file={WOFF2_OUT}",
            "--no-layout-closure",
            "--desubroutinize",
        ],
        check=True,
    )

    lines = [
        "/* Generated by scripts/build-hugeicons.py. Do not edit by hand. */",
        '@font-face{'
        'font-family:"hgi-stroke-rounded";'
        'font-display:block;'
        'src:url("hgi-stroke-rounded.woff2") format("woff2")}',
        ".hgi-stroke{"
        'font-family:"hgi-stroke-rounded"!important;'
        "font-style:normal;-webkit-font-smoothing:antialiased;"
        "-moz-osx-font-smoothing:grayscale;position:relative}",
        ".hgi-stroke:after{opacity:.4;position:absolute;left:0}",
    ]
    for icon in icons:
        for pseudo, body in rules[icon]:
            lines.append(f".hgi-stroke.{icon}:{pseudo}{{{body}}}")
    CSS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"  {len(icons)} icons, {len(codepoints)} glyphs")
    print(f"  wrote {WOFF2_OUT.relative_to(ROOT)} ({WOFF2_OUT.stat().st_size} bytes)")
    print(f"  wrote {CSS_OUT.relative_to(ROOT)} ({CSS_OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
