#!/usr/bin/env bash
# Work on the site in a copy that Syncthing never sees, then land the result.
#
# Every save in this folder reaches darkwoods within a second: images and videos
# under public/static go live on lowtechguys.com as they land, and watch-dev
# rebuilds dev.lowtechguys.com on every edit. A sandbox is a copy under
# ~/Temp/.claude-work (not synced), served from this Mac over Tailscale, and
# `land` copies back only the files the sandbox changed.
#
#   sandbox.sh new    NAME        copy the site, record what every file was
#   sandbox.sh serve  NAME [PORT] build, rebuild on change, serve on 0.0.0.0:PORT
#   sandbox.sh status NAME        what changed here, what changed upstream, conflicts
#   sandbox.sh land   NAME        copy changes back; refuses if upstream changed the same file
#   sandbox.sh drop   NAME        delete the sandbox
#   sandbox.sh list
#
# The reconcile is a three-way check on content hashes taken at `new`: a file
# lands only when the repo still holds what the sandbox started from (or already
# holds the sandbox's version). Build output never lands; darkwoods rebuilds it.
set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd -P)
ROOT=${SANDBOX_ROOT:-$HOME/Temp/.claude-work/lowtechguys-sandbox}

# Never copied, never compared: deps, VCS, Syncthing state, editor and tool litter.
COPY_EXCLUDES=(--exclude=/node_modules --exclude=/.venv --exclude=/.git --exclude=/.stfolder
  --exclude=/.stversions --exclude=/.stignore --exclude=/.playwright-mcp
  --exclude=/.cache --exclude='.DS_Store' --exclude='*.sync-conflict-*' --exclude='.syncthing.*')

# Generated by the build, so compared never: landing a locally built copy would
# ship dev-mode URLs.
is_generated() {
  case "$1" in
    public/*.html | public/*/*.html | public/*/*/*.html | public/*.xml | public/*/*.xml) return 0 ;;
    public/static/css/* | .css/* | public/static/img/private/* | public/*/presskit/*.zip) return 0 ;;
    *) return 1 ;;
  esac
}

die() { echo "sandbox: $*" >&2; exit 1; }
need_name() { [ -n "${1:-}" ] || die "missing NAME"; }

# path<TAB>sha1 for every tracked-by-sandbox file under $1
manifest() {
  (cd "$1" && find . \( -path ./node_modules -o -path ./.venv -o -path ./.git -o -path ./.stfolder \
      -o -path ./.stversions -o -path ./.playwright-mcp -o -path ./.cache \) -prune -o -type f -print |
    sed 's|^\./||' | while IFS= read -r f; do
      case "$f" in .DS_Store | */.DS_Store | .stignore | *.sync-conflict-* | */.syncthing.* | .syncthing.*) continue ;; esac
      is_generated "$f" && continue
      printf '%s\t%s\n' "$f" "$(shasum "$f" | cut -c1-40)"
    done | sort)
}

cmd_new() {
  need_name "${1:-}"; local dir="$ROOT/$1"
  [ -e "$dir" ] && die "$dir exists (status/land/drop it first)"
  mkdir -p "$dir"
  echo "Copying $REPO -> $dir/work"
  rsync -a "${COPY_EXCLUDES[@]}" "$REPO/" "$dir/work/"
  ln -s "$REPO/node_modules" "$dir/work/node_modules"
  ln -s "$REPO/.venv" "$dir/work/.venv"
  manifest "$REPO" >"$dir/base.tsv"
  # Its own history, so each review round can be committed and diffed. Never synced, never landed.
  (cd "$dir/work" && git init -q && git add -A && git commit -q -m "Sandbox base" >/dev/null) || true
  date '+%F %T' >"$dir/created"
  echo "Ready: $dir/work ($(wc -l <"$dir/base.tsv" | tr -d ' ') files recorded)"
}

cmd_serve() {
  need_name "${1:-}"; local dir="$ROOT/$1" port="${2:-4100}"
  [ -d "$dir/work" ] || die "no sandbox $1"
  cd "$dir/work"
  export NODE_ENV=development TAILWIND_MODE=build PYTHONWARNINGS=ignore
  unset DEPLOY_URL
  cat >"$dir/Caddyfile" <<EOF
{
	admin off
	auto_https off
}
http://:$port {
	root * $dir/work/public
	file_server
	try_files {path} {path}.html {path}/index.html
	header Cache-Control no-store
}
EOF
  caddy run --adapter caddyfile --config "$dir/Caddyfile" >"$dir/caddy.log" 2>&1 &
  local srv=$!
  trap 'kill $srv 2>/dev/null; exit 0' INT TERM EXIT
  local host; host=$(tailscale status --self --json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || hostname -s)
  make -j html css private-img >/dev/null || true
  echo "Serving $dir/work/public on http://$host:$port/ (Ctrl-C stops)"
  local stamp; stamp=$(mktemp)
  while true; do
    if find src stylus private tailwind.config.js -type f ! -name '.*' -newer "$stamp" 2>/dev/null | grep -q .; then
      touch "$stamp"; sleep 1
      make -j html css private-img 2>&1 | grep -v '^make' || true
      # `make css` only reruns when stylus or the config change, but Tailwind JIT has to
      # rescan the pages whenever a class is added, so run it after every page build.
      npx -y tailwindcss --postcss --jit -i .css/app.css -o public/static/css/app.css >/dev/null 2>&1 || true
    fi
    sleep 1
  done
}

# Prints one line per changed file: <state> <path>
#   land      sandbox changed it, repo did not
#   same      both changed it identically
#   conflict  both changed it differently
#   upstream  repo changed it, sandbox did not (land leaves it alone)
diff_states() {
  local dir="$1" work repo
  work=$(mktemp); repo=$(mktemp)
  manifest "$dir/work" >"$work"
  manifest "$REPO" >"$repo"
  python3 - "$dir/base.tsv" "$work" "$repo" <<'EOF'
import sys
b, w, r = ({l.split("\t")[0]: l.rstrip("\n").split("\t")[1] for l in open(f) if "\t" in l} for f in sys.argv[1:])
for p in sorted(set(b) | set(w) | set(r)):
    B, W, R = b.get(p), w.get(p), r.get(p)
    if W == B and R == B: continue
    print("upstream" if W == B else "same" if R == W else "land" if R == B else "conflict", p)
EOF
  rm -f "$work" "$repo"
}

cmd_status() {
  need_name "${1:-}"; local dir="$ROOT/$1"
  [ -d "$dir/work" ] || die "no sandbox $1"
  echo "Sandbox $1, created $(cat "$dir/created")"
  diff_states "$dir" | awk '{ n[$1]++; print } END { if (!NR) print "no changes" }'
}

cmd_land() {
  need_name "${1:-}"; local dir="$ROOT/$1"
  [ -d "$dir/work" ] || die "no sandbox $1"
  local states; states=$(diff_states "$dir")
  if grep -q '^conflict ' <<<"$states"; then
    grep '^conflict ' <<<"$states"
    die "upstream changed these too; merge them by hand in $dir/work (or the repo), then land again"
  fi
  local n=0
  while read -r state p; do
    [ "$state" = land ] || continue
    if [ -e "$dir/work/$p" ]; then
      mkdir -p "$REPO/$(dirname "$p")"
      cp -p "$dir/work/$p" "$REPO/$p"; echo "  + $p"
    else
      rm -f "$REPO/$p"; echo "  - $p"
    fi
    n=$((n + 1))
  done <<<"$states"
  echo "Landed $n file(s). Syncthing carries them to darkwoods now."
  # The sandbox now matches the repo for everything it landed.
  manifest "$REPO" >"$dir/base.tsv"
}

cmd_drop() {
  need_name "${1:-}"; local dir="$ROOT/$1"
  [ -d "$dir" ] || die "no sandbox $1"
  local pending; pending=$(diff_states "$dir" | grep -E '^(land|conflict) ' || true)
  if [ -n "$pending" ] && [ "${FORCE:-0}" != 1 ]; then
    echo "$pending"; die "unlanded changes; land them or pass FORCE=1"
  fi
  rm -rf "$dir"; echo "Dropped $1"
}

cmd_list() { [ -d "$ROOT" ] && for d in "$ROOT"/*/; do [ -d "$d" ] && echo "$(basename "$d")  $(cat "$d/created" 2>/dev/null)"; done; true; }

case "${1:-}" in
  new | serve | status | land | drop | list) c=$1; shift; "cmd_$c" "$@" ;;
  *) sed -n '2,20p' "$0"; exit 1 ;;
esac
